### PR TITLE
cmd: gdb: update elf path to work with new `script.gdb`

### PR DESCRIPTION
**Pull request by beezow**
Hubris PR https://github.com/rivosinc/hubris/pull/76 and https://github.com/rivosinc/hubris/pull/73 broke `humility gdb` by changing the paths in the `scripts.gdb`.  This change adds support for this change.

The caveat here is that it breaks support with all hubris archives predating hubris hash `f1e8bce17758e1b57aaba340370f21a3bf142e0d` on rivos/main and `ba2b47e9a10308c6cecef138e1a31da606714e62` on rivos/main-rv64.

### CODE REVIEW

**Comment by beezow** [comment]
When those PRs initially came through, I was not able to replicate the bug both @richard-rivos and @furquan-rivos reported.  Were you guys manually sourcing `script.gdb` or were you using `humility gdb`?  I suspect this is the difference as things always worked fine for me...

**Comment by beezow** [comment]
The alternative to this is reverting those PRs and telling everyone to use humility to launch GDB.

**Comment by furquan-rivos** [comment]
> When those PRs initially came through, I was not able to replicate the bug both @richard-rivos and @furquan-rivos reported. Were you guys manually sourcing `script.gdb` or were you using `humility gdb`? I suspect this is the difference as things always worked fine for me...

I followed the steps that @richard-rivos provided i.e. manually sourcing script.gdb. I think that is the reason why upstream oxide folks haven't run into this issue as well? i.e. they are using humility gdb and not manually source script.gdb.

**Review by furquan-rivos — DISMISSED** [review]

**Comment by furquan-rivos** [comment]
> The alternative to this is reverting those PRs and telling everyone to use humility to launch GDB.

Is it possible to parse the gdb script to determine where the elfs are expected to be? That way we can make humility work with old and new scripts. Not sure how easy/difficult it is though.

**Comment by beezow** [comment]
> > The alternative to this is reverting those PRs and telling everyone to use humility to launch GDB.
> 
> Is it possible to parse the gdb script to determine where the elfs are expected to be? That way we can make humility work with old and new scripts. Not sure how easy/difficult it is though.

I think we should do that.  We should be able to regex for `add-symbol-file` and extract the paths.

**Comment by ghost** [comment]
You're correct @beezow, I was manually sourcing the scripts at the time. I was unaware of 'humility gdb' and had been avoiding the use of humility all together due to lack of support on rv64 targets.

I'm somewhat confused how 'humility gdb' worked before my changes in script.gdb generation though as the paths within the generated '.zip' archives don't seem to match those in 'script.gdb' (see below):

```
richard@<hostname> default % tree build-demo-rv64-qemu-virt
build-demo-rv64-qemu-virt
├── README.TXT
├── app.toml
├── chip.toml
├── debug
│   ├── openocd.cfg
│   ├── openocd.gdb
│   ├── qemu.sh
│   └── script.gdb
├── elf
│   ├── kernel
│   └── task
│       ├── idle
│       ├── jefe
│       ├── ping
│       └── pong
├── git-rev
└── img
    ├── combined.bin
    ├── combined.elf
    ├── combined.ihex
    ├── combined.srec
    ├── final.bin
    ├── final.elf
    ├── final.ihex
    └── final.srec

4 directories, 21 files
```

Given that {image_name} ('default' by default) isn't represented at all within the '.zip' archives, I wonder if it's worth generating seperate 'script.gdb's for inclusion within the archives as part of the Hubris build.

**Comment by beezow** [comment]
> You're correct @beezow, I was manually sourcing the scripts at the time. I was unaware of 'humility gdb' and had been avoiding the use of humility all together due to lack of support on rv64 targets.
> 
> I'm somewhat confused how 'humility gdb' worked before my changes in script.gdb generation though as the paths within the generated '.zip' archives don't seem to match those in 'script.gdb' (see below):
> 
> ```
> richard@<hostname> default % tree build-demo-rv64-qemu-virt
> build-demo-rv64-qemu-virt
> ├── README.TXT
> ├── app.toml
> ├── chip.toml
> ├── debug
> │   ├── openocd.cfg
> │   ├── openocd.gdb
> │   ├── qemu.sh
> │   └── script.gdb
> ├── elf
> │   ├── kernel
> │   └── task
> │       ├── idle
> │       ├── jefe
> │       ├── ping
> │       └── pong
> ├── git-rev
> └── img
>     ├── combined.bin
>     ├── combined.elf
>     ├── combined.ihex
>     ├── combined.srec
>     ├── final.bin
>     ├── final.elf
>     ├── final.ihex
>     └── final.srec
> 
> 4 directories, 21 files
> ```
> 
> Given that {image_name} ('default' by default) isn't represented at all within the '.zip' archives, I wonder if it's worth generating seperate 'script.gdb's for inclusion within the archives as part of the Hubris build.

Within humility, it created the folder structure that we saw within the `script.gdb`.  I don't think it would be worth generating two seperate `script.gdb` files since we can just create arbitrary directories within humility.

**Comment by beezow** [comment]
I do wonder how this change plays with the arm multi-image builds though.  I need to look and see what the generated `script.gdb` are for those.

**Comment by furquan-rivos** [comment]
> I do wonder how this change plays with the arm multi-image builds though. I need to look and see what the generated `script.gdb` are for those.

Did this work fine?

**Review by furquan-rivos — APPROVED** [review]

**Comment by beezow** [comment]
> > I do wonder how this change plays with the arm multi-image builds though. I need to look and see what the generated `script.gdb` are for those.
> 
> Did this work fine?

This mantains the previous behavior, but have to look into how things are in the `script.gdb` for multi image builds.  If that needs modification, it would be a new feature so I made https://rivosinc.atlassian.net/browse/SW-982 to track it.

**Pull request merged**
