### PR TITLE
Merge in upstream changes

### PR DESCRIPTION
**Pull request by beezow**
The biggest change that is relevant to us is the introduction of the repl.

### CODE REVIEW

**Review by furquan-rivos — DISMISSED** [review]
rubberstamp approval

**Review by FawazTirmizi — DISMISSED** [review]

**Comment by beezow** [comment]
I redid the merge since github didn't want to merge it into main for some reason, the result is identical. Lets hope it works this time...

**Review by FawazTirmizi — APPROVED** [review]

**Comment by beezow** [comment]
This is a clean fast forward on the command line...

**Review by furquan-rivos — APPROVED** [review]

**Comment by beezow** [comment]
I am just going to merge and push to main manually, unless anyone has objections.  @rivosinc/hubris-humility-maintainers

**Comment by furquan-rivos** [comment]
> I am just going to merge and push to main manually, unless anyone has objections. @rivosinc/hubris-humility-maintainers

SGTM.

**Comment by beezow** [comment]
Manually merged, I think it was related to the merge commit, but I couldn't find the setting to allow it.

**Pull request closed without merging**
